config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
] + static('media/', document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index_view, name="index"),
    path("playground/", views.playground_view, name="playground"),
    path("blog/", views.blog_view, name="blog"),
    path("blog/<int:artigo_id>", views.article_view, name="article"),
    path("blog/like/<int:artigo_id>", views.like_view, name="like"),
    path("blog/comment/<int:artigo_id>", views.comment_view, name="comment"),
    path("blog/comment/<int:comentario_id>/like", views.comment_like_view, name="comment_like"),
    path("blog/delete/<int:artigo_id>", views.delete_article_view, name="delete"),
    path("admin/", views.admin_view, name="admin"),
    path("blog/new/", views.new_article_view, name="new"),
    path("blog/edit/<int:artigo_id>", views.edit_article_view, name="edit"),
    path("login/", views.login_view, name="login"),
    path("login/<str:url>", views.login_view, name="login_args")
]

portfolio/models.py
from django.db import models


class Area(models.Model):
    nome = models.CharField(max_length=80)

    def __str__(self) -> str:
        return self.nome


class Autor(models.Model):
    nome = models.CharField(max_length=80)
    areas = models.ManyToManyField(Area)

    def __str__(self) -> str:
        return self.nome


class Pessoa(models.Model):
    nome = models.CharField(max_length=80)
    linkedin = models.TextField(null=True, blank=True)
    portfolio = models.TextField(null=True, blank=True)

    def __str__(self) -> str:
        return self.nome


class Artigo(models.Model):
    nome = models.CharField(max_length=80)
    autor = models.ForeignKey(Autor, on_delete=models.CASCADE)
    texto = models.TextField()
    imagem = models.ImageField(upload_to='imagens/', null=True, blank=True)
    area = models.ForeignKey(Area, on_delete=models.CASCADE)
    likes = models.IntegerField(default=0)

    def __str__(self) -> str:
        return f'{self.autor.nome}: {self.nome}'


class Comentario(models.Model):
    artigo = models.ForeignKey(Artigo, on_delete=models.CASCADE)
    autor = models.CharField(max_length=80)
    texto = models.TextField()
    likes = models.IntegerField(default=0)

    def __str__(self) -> str:
        return f'{self.artigo.nome}: {self.autor}: {self.likes}'


class Cadeira(models.Model):
    nome = models.TextField()


class Projeto(models.Model):
    participantes = models.ForeignKey(Pessoa, on_delete=models.CASCADE)
    nome = models.TextField()
    descricao = models.TextField(max_length=500)
    imagem = models.ImageField(upload_to='imagens/', null=True, blank=True)
    ano = models.IntegerField()
    cadeira = models.ForeignKey(Cadeira, null=True, blank=True, on_delete=models.CASCADE)
    git = models.TextField(null=True, blank=True)


class PrevisaoMetereologica(models.Model):
    temp_min = models.IntegerField()
    temp_max = models.IntegerField()

    def __str__(self):
        return f'Temperatura Mínima: {self.temp_min}, Temperatura Máxima: {self.temp_max}'


class TFC(models.Model):
    titulo = models.TextField()
    descricao = models.TextField(max_length=500)
    autor = models.ManyToManyField(Pessoa, related_name='autor')
    orientador = models.ManyToManyField(Pessoa, related_name='orientador')
    ano = models.IntegerField()
    link = models.TextField()
    github = models.TextField(null=True, blank=True)
    video = models.TextField(null=True, blank=True)

portfolio/forms.py
from django.forms import ModelForm

from .models import Artigo, Comentario


class ArtigoForm(ModelForm):
    class Meta:
        model = Artigo
        fields = '__all__'


class ComentarioForm(ModelForm):
    class Meta:
        model = Comentario
        fields = ['autor', 'texto']

portfolio/views.py
import json

from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import AnonymousUser, User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.csrf import csrf_exempt

from .models import Area, Artigo, Comentario, Projeto, TFC
from .forms import ArtigoForm, ComentarioForm


# Create your views here.

def blog_view(request):
    areas = Area.objects.all()
    return render(request, 'portfolio/blog.html', context={'areas': areas})


def index_view(request):
    return render(request, 'portfolio/index.html', context={'projects': Projeto.objects.all(), 'tfcs': TFC.objects.all()})


def playground_view(request):
    return render(request, 'portfolio/playground.html')


def admin_view(request):
    return render(request, 'portfolio/admin.html')


@login_required()
def new_article_view(request):
    if request.method == "POST":
        form = ArtigoForm(request.POST, request.FILES)

        if not form.is_valid():
            return HttpResponse(status=400)

        form.save()

        return redirect('blog')

    return render(request, 'portfolio/new_article.html', context={'form': ArtigoForm()})


@login_required()
def edit_article_view(request, artigo_id):
    if request.method == "POST":
        inst = get_object_or_404(Artigo, id=artigo_id)
        form = ArtigoForm(request.POST, request.FILES, instance=inst)

        if not form.is_valid():
            return HttpResponse(status=400)

        form.save()

        return redirect('article', artigo_id=artigo_id)

    inst = get_object_or_404(Artigo, id=artigo_id)
    return render(request, 'portfolio/edit_article.html', context={'form': ArtigoForm(instance=inst), 'artigo': inst})


@login_required()
def delete_article_view(request, artigo_id):
    obj = get_object_or_404(Artigo, id=artigo_id)
    obj.delete(keep_parents=True)
    return redirect('blog')


def article_view(request, artigo_id):
    artigo = get_object_or_404(Artigo, id=artigo_id)

    return render(request, 'portfolio/article.html', context={'artigo': artigo, 'form': ComentarioForm()})


def like_view(request, artigo_id):
    artigo = get_object_or_404(Artigo, id=artigo_id)

    artigo.likes += 1
    artigo.save()

    response = HttpResponse(artigo.likes)

    return response


def comment_view(request, artigo_id):
    artigo = get_object_or_404(Artigo, id=artigo_id)

    form = ComentarioForm(request.POST)
    if not form.is_valid():
        return HttpResponse(status=400)

    comentario = form.save(commit=False)
    comentario.artigo = artigo

    comentario.save()
    form.save_m2m()

    return redirect('article', artigo_id=artigo_id)


def comment_like_view(request, comentario_id):
    comentario = get_object_or_404(Comentario, id=comentario_id)

    comentario.likes += 1
    comentario.save()

    return HttpResponse(str(comentario.likes))


@csrf_exempt
def login_view(request, url='index'):
    if request.method == 'POST' and request.POST.get('username', None) and request.POST.get('password', None):
        user = authenticate(username=request.POST['username'], password=request.POST['password'])

        if type(user) is not User:
            return render(request, 'portfolio/login.html', context={'next': request.POST.get('next', None)})

        login(request, user)

        return redirect(request.POST['next'] if request.POST.get('next', None) else url)

    return render(request, 'portfolio/login.html', context={'next': request.GET.get('next', None)})

blog/templates/blog/admin.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Admin</title>
    <link rel="stylesheet" href="{% static 'blog/css/global.css' %}">
</head>
<body>
    <h1>Blog</h1>

    form[action="/
</body>
</html>

blog/templates/blog/index.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blog</title>
    <link rel="stylesheet" href="{% static 'blog/css/global.css' %}">
</head>
<body>
    <h1>Blog</h1>
    {% for area in areas %}
        <h1>{{ area.nome }}</h1>
        <div>
        {% for artigo in area.artigo_set.all %}
            <div>
                <p>{{ artigo.nome }}</p>
                <p>{{ artigo.texto|truncatechars:25 }}</p>
            </div>
        {% endfor %}
        </div>
    {% endfor %}
</body>
</html>

blog/templates/blog/new_article.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Admin</title>
    <link rel="stylesheet" href="{% static 'blog/css/global.css' %}">
</head>
<body>
    <h1>Blog</h1>

    <form action="{% url 'new' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}

        <input type="submit" value="Submeter">
    </form>
</body>
</html>

portfolio/templates/portfolio/admin.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Admin</title>
    <link rel="stylesheet" href="{% static 'portfolio/css/global.css' %}">
</head>
<body>
    <h1>Blog</h1>
</body>
</html>

portfolio/templates/portfolio/article.html
{% extends 'portfolio/skel.html' %}
{% load static %}

{% block header %}
    <link rel="stylesheet" href="{% static 'portfolio/css/blog.css' %}">
{% endblock %}

{% block content %}
<div class="container dark">
    <div class="row">
        <h1>Blog</h1>
        <a href="{% url 'edit' artigo.id %}" class="right vert-end">Editar artigo</a>
    </div>

    <div class="artigo-container">
        <h2>{{ artigo.nome }}</h2>
        {% if artigo.imagem %}
            <img src="{{ artigo.imagem.url }}" alt="" class="artigo-imagem">
        {% endif %}
        <p>{{ artigo.texto }}</p>
    </div>

    <button onclick="comecarComentario()" style="width: fit-content; margin: 2% auto;">Novo comentário</button>

    <form action="{% url 'comment' artigo.id %}" method="post" name="form" class="hidden artigo-container">
        {% csrf_token %}

        {{ form.as_p }}

        <input type="submit" value="Submeter!">
    </form>

    <div class="artigo-container">
        {% for c in artigo.comentario_set.all %}
            <div class="artigo">
                <div>
                    <h2>{{ c.autor }}</h2>
                    <p>{{ c.texto }}</p>
                </div>
                <div class="like">
                    <img src="{% static 'portfolio/img/like.png' %}" alt="" onclick="like(this, {{ c.id }})">
                    <span>{{ c.likes }}</span>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

<script src="{% static 'portfolio/js/article.js' %}"></script>
{% endblock %}

portfolio/templates/portfolio/blog.html
{% extends 'portfolio/skel.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'portfolio/css/blog.css' %}">
{% endblock %}

{% block content %}
<div class="container dark">
    <div class="row">
        <h1>Blog</h1>
        <a href="{% url 'new' %}" class="right vert-end">Novo artigo</a>
    </div>
    {% for area in areas %}
        <h2>{{ area.nome }}</h2>
        <div class="artigo-container">
        {% for artigo in area.artigo_set.all %}
            <div class="artigo">
                {% if artigo.imagem %}
                    <img src="{{ artigo.imagem.url }}" alt="">
                {% endif %}
                <div>
                    <a href="{% url 'article' artigo.id %}"><h2>{{ artigo.nome }}</h2></a>
                    <p>{{ artigo.texto }}</p>
                </div>
                <div class="like">
                    <img src="{% static 'portfolio/img/like.png' %}" alt="" onclick="like(this, {{ artigo.id }})">
                    <span>{{ artigo.likes }}</span>
                </div>
            </div>
        {% endfor %}
        </div>
    {% endfor %}
</div>

<script src="{% static 'portfolio/js/global.js' %}"></script>
<script src="{% static 'portfolio/js/blog.js' %}"></script>
{% endblock %}

portfolio/templates/portfolio/edit_article.html
{% extends 'portfolio/skel.html' %}
{% load static %}

{% block header %}
<a href="{% url 'index' %}#second">Sobre</a>
<a href="{% url 'index' %}#third">Projetos</a>
<a href="{% url 'index' %}#forth">PW</a>
<a href="{% url 'playground' %}">Playground</a>
{% endblock %}

{% block menu %}
<a href="{% url 'index' %}#second">Sobre</a>
<a href="{% url 'index' %}#third">Projetos</a>
<a href="{% url 'index' %}#forth">PW</a>
<a href="{% url 'playground' %}">Playground</a>
{% endblock %}

{% block content %}
<div class="container dark">
    <div class="row">
        <h1>Editar artigo</h1>
    </div>

    <form action="{% url 'edit' artigo.id %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}

        <input type="submit" value="Submeter">
    </form>
    <a href="{% url 'delete' artigo.id %}">Apagar</a>
</div>

<script src="{% static 'portfolio/js/global.js' %}"></script>
{% endblock %}

portfolio/templates/portfolio/index.html
{% extends 'portfolio/skel.html' %}
{% load static %}

{% block content %}
<div class="parent">
    <div class="dark container" id="first">
        <span id="insp">Estudante de dia<br>Programador à noite</span>
    </div>

    <img src="{% static 'portfolio/img/mouse-scroll.svg' %}" height="40" width="40">
</div>

<article class="dark container" id="second">
    <h1>Sobre</h1>

    <h2>Educação</h2>

    <div class="content">
        <ul>
            <li>Secundário: Escola Secundária Ibn Mucana</li>
            <li>Curso: Engenharia Informática 2º Ano ULHT</li>
        </ul>
    </div>

    <h2>Aptidões</h2>

    <div class="content">
        <div class="bar-container">
            <div>
                <span>Português: 100%</span>
                <div class="bar-parent" data-pct="100">
                    <div class="bar"></div>
                </div>
            </div>
            <div>
                <span>Inglês: 90%</span>
                <div class="bar-parent" data-pct="90">
                    <div class="bar"></div>
                </div>
            </div>
            <div>
                <span>Kotlin: 85%</span>
                <div class="bar-parent" data-pct="85">
                    <div class="bar"></div>
                </div>
            </div>
            <div>
                <span>Java: 85%</span>
                <div class="bar-parent" data-pct="85">
                    <div class="bar"></div>
                </div>
            </div>
            <div>
                <span>C: 80%</span>
                <div class="bar-parent" data-pct="80">
                    <div class="bar"></div>
                </div>
            </div>
            <div>
                <span>HTML/CSS/JS: 60%</span>
                <div class="bar-parent" data-pct="60">
                    <div class="bar"></div>
                </div>
            </div>
            <div>
                <span>Clojure: 40%</span>
                <div class="bar-parent" data-pct="40">
                    <div class="bar"></div>
                </div>
            </div>
        </div>
    </div>
</article>
</div>

<article class="dark container" id="third">
    <h1>Projetos</h1>

    <div class="content">
        {% for p in projects %}
        <a class="project dark" {% if p.git %} href="{{ p.git }}" {% endif %}>
            <div {% if p.imagem %} style="background-image: url('{{ p.imagem.url }}'); background-size: cover" {% endif %}></div>
            <div>
                <p>{{ p.nome }}</p>
                <p>{{ p.descricao|truncatechars:30 }}</p>
            </div>
        </a>
        {% endfor %}
    </div>

    <h2>TFCs interessantes</h2>
    <div class="content">
        {% for p in tfcs %}
        <a class="tfc dark" href="{{ p.link }}">
            <div></div>
            <div>
                <p>{{ p.titulo }}</p>
                <p>{{ p.descricao|truncatechars:30 }}</p>
            </div>
        </a>
        {% endfor %}
    </div>
</article>

<article class="dark container" id="forth">
    <h1>Programação Web</h1>

    <div class="content">
        <a class="project dark" href="https://jajms.pythonanywhere.com/index.html">
            <div></div>
            <div>
                <p>Lab 1/2</p>
            </div>
        </a>
        <a class="project dark" href="https://jajms.pythonanywhere.com/lab3/index.html">
            <div></div>
            <div>
                <p>Lab 3</p>
            </div>
        </a>
        <a class="project dark" href="https://jajms.pythonanywhere.com/lab4/index.html">
            <div></div>
            <div>
                <p>Lab 4</p>
            </div>
        </a>
    </div>
</article>

<script src="{% static 'portfolio/js/global.js' %}"></script>
<script src="{% static 'portfolio/js/index.js' %}"></script>
{% endblock %}

portfolio/templates/portfolio/login.html
{% extends 'portfolio/skel.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'portfolio/css/login.css' %}">
{% endblock %}

{% block content %}
<form class="container dark login" action="{% url 'login' %}" method="post">
    <input type="text" name="next" value="{{ next }}" style="display: none">
    <input type="text" name="username" placeholder="Username">
    <input type="password" name="password" placeholder="Password">
    <input type="submit" value="Login">
</form>
{% endblock %}

portfolio/templates/portfolio/new_article.html
{% extends 'portfolio/skel.html' %}
{% load static %}

{% block header %}
<a href="{% url 'index' %}#second">Sobre</a>
<a href="{% url 'index' %}#third">Projetos</a>
<a href="{% url 'index' %}#forth">PW</a>
<a href="{% url 'playground' %}">Playground</a>
{% endblock %}

{% block menu %}
<a href="{% url 'index' %}#second">Sobre</a>
<a href="{% url 'index' %}#third">Projetos</a>
<a href="{% url 'index' %}#forth">PW</a>
<a href="{% url 'playground' %}">Playground</a>
{% endblock %}

{% block content %}
<div class="container dark">
    <div class="row">
        <h1>Novo artigo</h1>
    </div>

    <form action="{% url 'new' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}

        <input type="submit" value="Submeter">
    </form>
</div>

<script src="{% static 'portfolio/js/global.js' %}"></script>
{% endblock %}

portfolio/templates/portfolio/playground.html
{% extends 'portfolio/skel.html' %}
{% load static %}

{% block header %}{% endblock %}
{% block menu %}{% endblock %}

{% block content %}
<main>
    <div id="pg-first" class="container dark">
        <span id="date"></span>
        <div id="calc">
            <input type="text" id="resultado">
            <button>7</button> <button>8</button> <button>9</button> <button>+</button>
            <button>4</button> <button>5</button> <button>6</button> <button>-</button>
            <button>1</button> <button>2</button> <button>3</button> <button>*</button>
            <button id="clear">C</button> <button>0</button> <button id="calcButton">=</button> <button>/</button>
        </div>
    </div>

    <div class="container dark" style="min-height: unset">
        <img src="{% static 'portfolio/img/tempo.png' %}" alt="" style="width: 30%; margin: 0 auto;">
        <p style="margin: 0.5% auto 0 auto;">Gráfico das temperaturas máximas e mínimas nos próximos 7 dias</p>
    </div>

    <div id="pg-second" class="container dark">
        <div>
            <label for="nome">Insira o seu nome:</label>
            <br>
            <input type="text" name="nome" id="nome">
        </div>
    </div>

    <div id="pg-third" class="container dark">
        <div class="container dark" id="img-container">
            <img src="{% static 'portfolio/img/bg.jpg' %}" alt="">

            <span id="img-lbl"></span>
        </div>

        <br>

        <div>
            <label for="img-txt">Insira uma frase sobre a imagem:</label>
            <br>
            <input type="text" id="img-txt">
        </div>
    </div>

    <div id="pg-forth" class="container dark">
        <iframe width="560" height="315" src="https://www.youtube.com/embed/IWVJq-4zW24?controls=0?autoplay=1&mute=1" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
    </div>

    <div id="pg-forth" class="container dark">
        <iframe width="560" height="315" src="https://www.youtube.com/embed/M3Mfz8liERQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
    </div>
</main>

<script src="{% static 'portfolio/js/playground.js' %}"></script>
{% endblock %}

portfolio/templates/portfolio/skel.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Portfolio</title>

    <link rel="stylesheet" href="{% static 'portfolio/css/global.css' %}">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />

    <style>
        .material-symbols-outlined {
          font-variation-settings:
          'FILL' 1,
          'wght' 400,
          'GRAD' 0,
          'opsz' 48
        }
    </style>

    {% block head %}{% endblock %}
</head>
<body class="dark">
    <header id="header" class="dark">
        <a href="{% url 'index' %}">JTM</a>
        
        <div class="center" id="links">
            {% block header %}
            <a href="{% url 'index' %}#second">Sobre</a>
            <a href="{% url 'index' %}#third">Projetos</a>
            <a href="{% url 'index' %}#forth">PW</a>
            <a href="{% url 'playground' %}">Playground</a>
            <a href="{% url 'blog' %}">Blog</a>
            {% endblock %}
        </div>

        <div class="right">
            <button id="theme-toggle" class="image-button" onclick="toggle_theme()">
                <span class="material-symbols-outlined dark">light_mode</span>
            </button>

            <button id="menu-toggle" class="image-button" onclick="toggle_menu()">
                <span class="material-symbols-outlined dark">menu</span>
            </button>
        </div>

        <div id="menu" class="dark">
            <button class="image-button" onclick="toggle_menu()">
                <span class="material-symbols-outlined dark">close</span>
            </button>
            {% block menu %}
            <a href="{% url 'index' %}#second">Sobre</a>
            <a href="{% url 'index' %}#third">Projetos</a>
            <a href="{% url 'index' %}#forth">PW</a>
            <a href="{% url 'playground' %}">Playground</a>
            <a href="{% url 'blog' %}">Blog</a>
            {% endblock %}
        </div>
    </header>

    {% block content %}{% endblock %}

    {% block footer %}
        <footer class="dark">
            <span>João Marques, a22108693 Engenharia Informática</span>
        </footer>
    {% endblock %}

    <script src="{% static 'portfolio/js/theme.js' %}"></script>
</body>